apiVersion: v1
kind: Template
labels:
  demo: coolstore-microservice
metadata:
  annotations:
    description: CoolStore demo microservices application buildconfigs template
    iconClass: icon-java
    tags: microservice,jboss,spring
  name: coolstore-builds
objects:
# Onboarding Service
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: onboarding
  spec:
    tags:
    - name: latest
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: onboarding
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: onboarding:latest
    source:
      contextDir: onboarding-service
      git:
        ref: ${GIT_REF}
        uri: ${GIT_URI}
      type: http
    strategy:
      type: Docker
      dockerStrategy:
        noCache: true
        dockerfilePath: Dockerfile
    resources:
      limits:
        cpu: 1
        memory: "2Gi"
      requests:
        cpu: "200m"
        memory: "1Gi"
parameters:
- description: Git source URI for application
  displayName: Git source repository
  name: GIT_URI
  required: true
  value: https://github.com/lapd-viosoft/coolstore-microservice
- description: Git branch/tag reference
  displayName: Git branch/tag reference
  name: GIT_REF
  required: true
  value: master
- description: Maven mirror url. If nexus is deployed locally, use nexus url (e.g. http://nexus.ci:8081/content/groups/public/)
  displayName: Maven mirror url
  name: MAVEN_MIRROR_URL
- description: NPM mirror url. If nexus is deployed locally, use nexus url (e.g. http://nexus.ci:8081/repository/npm/)
  displayName: NPM mirror url
  name: NPM_MIRROR
- description: Bower mirror url. If nexus is deployed locally, use nexus url (e.g. http://nexus.ci:8081/repository/bower-mirror/)
  displayName: Bower mirror url
  name: BOWER_MIRROR
- description: Decision Server Coolstore Rules Container Spec
  name: KIE_CONTAINER_DEPLOYMENT
  required: true
  value: CoolStoreRulesContainer=com.redhat:coolstore:2.0.0
