apiVersion: v1
kind: Template
labels:
  demo: coolstore-microservice
  template: onboarding-bluegreen
metadata:
  annotations:
    description: This template is a complement to coolstore-builds and coolstore-deployments templates
    iconClass: icon-java
    tags: microservice,jboss,spring
  name: onboarding-bluegreen
objects:
# Onboarding Service - Blue
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: onboarding-blue
    labels:
      application: onboarding
      variant: blue
  spec:
    replicas: 1
    selector:
      deploymentconfig: onboarding-blue
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          application: onboarding
          variant: blue
          deploymentconfig: onboarding-blue
        name: onboarding-blue
      spec:
        containers:
        - env:
          - name: OPENSHIFT_KUBE_PING_LABELS
            value: application=onboarding-blue
          - name: OPENSHIFT_KUBE_PING_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: ' '
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                - echo Shutdown
          name: onboarding
          ports:
          - containerPort: 9090
            name: http
            protocol: TCP
          resources:
            limits:
              cpu: 2
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 75
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - onboarding
        from:
          kind: ImageStreamTag
          name: onboarding:${APP_VERSION_BLUE}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: onboarding-live
      application: onboarding
      variant: blue
    name: onboarding-blue
  spec:
    ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
    selector:
      deploymentconfig: onboarding-blue
# Onboarding Service - Green
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: onboarding-green
    labels:
      application: onboarding
      variant: green
  spec:
    replicas: 1
    selector:
      deploymentconfig: onboarding-green
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          application: onboarding
          variant: green
          deploymentconfig: onboarding-green
        name: onboarding-green
      spec:
        containers:
        - env:
          - name: OPENSHIFT_KUBE_PING_LABELS
            value: application=onboarding-green
          - name: OPENSHIFT_KUBE_PING_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: ' '
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                - echo shutdown
          name: onboarding
          ports:
          - containerPort: 9090
            name: http
            protocol: TCP
          resources:
            limits:
              cpu: 2
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 75
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - onboarding
        from:
          kind: ImageStreamTag
          name: onboarding:${APP_VERSION_GREEN}
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: onboarding-idle
      application: onboarding
      variant: green
    name: onboarding-green
  spec:
    ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
    selector:
      deploymentconfig: onboarding-green
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      application: onboarding
      variant: green
    name: onboarding
  spec:
    host: onboarding-${HOSTNAME_SUFFIX}
    alternateBackends:
    - name: onboarding-green
      weight: "0"
    to:
      kind: Service
      name: onboarding-blue
      weight: "100"
parameters:
- description: Hostname suffix used for routes e.g. onboarding-<HOSTNAME_SUFFIX>
  displayName: Hostname suffix used for routes
  name: HOSTNAME_SUFFIX
  required: true
- description: CoolStore application image version to be deployed (imagestreams should exist)
  displayName: CoolStore blue (existing) image version
  name: APP_VERSION_BLUE
  required: true
  value: prod-blue
- description: CoolStore application image version to be deployed (imagestreams should exist)
  displayName: CoolStore green (new) image version
  name: APP_VERSION_GREEN
  required: true
  value: prod-green
